# Tutorial 56: Nominal Diameter Tables

## SIR 3S Toolkit

### Regular Import/Init

In [1]:
SIR3S_SIRGRAF_DIR = r"C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2" #change to local path

In [2]:
from sir3stoolkit.core import wrapper

In [3]:
wrapper

In [4]:
wrapper.Initialize_Toolkit(SIR3S_SIRGRAF_DIR)

### Additional Import/Init for Dataframes class

In [5]:
from sir3stoolkit.mantle.dataframes import SIR3S_Model_Dataframes

In [6]:
s3s = SIR3S_Model_Dataframes()

Initialization complete

## Additional

In [7]:
import pandas as pd
from shapely.geometry import Point
import re
import folium
from folium.plugins import HeatMap
import numpy as np
import geopandas as gpd
from shapely import wkt
import matplotlib.pyplot as plt
import contextily as cx

# Open Model

In [8]:
s3s.OpenModel(dbName=r"../Tutorial051_Assets/Toolkit_Tutorial51_Model.db3",
              providerType=s3s.ProviderTypes.SQLite,
              Mid="M-1-0-1",
              saveCurrentlyOpenModel=False,
              namedInstance="",
              userID="",
              password="")

Model is open for further operation

# View Nominal Diameter Tables

We can use the function [get_dataframes_from_nominal_diameter_tables()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.get_dataframes_from_nominal_diameter_tables) to obtain a dictionary of all nominal diameter tables.

In [ ]:
_, dfs, tks = s3s.get_dataframes_from_nominal_diameter_tables(table_type=s3s.ObjectTypes.PipeTable)

In [11]:
for id, tk in enumerate(tks):
    print(f"{id}: {tk}: {s3s.GetValue(tk, 'Name')[0]}")

0: 4929824488020291605: STDROHR
1: 4862079620528720750: FLEXWELL-F
2: 5157457566256524875: STDROHR_2
3: 4927972999088213410: KMR

In [28]:
s3s.GetPropertiesofElementType(s3s.ObjectTypes.PipeTable_Row)

['Name',
 'Fk',
 'Dn',
 'Di',
 'Da',
 'S',
 'Wsteig',
 'Wtiefe',
 'Kt',
 'Pn',
 'Ausfallzeit',
 'Reparatur',
 'Rehabilitation',
 'Tk',
 'Pk',
 'InVariant']

## STDROHR

In [12]:
dfs[tks[0]].head(3)

,tk_merge,Name,Fk,Dn,Di,Da,S,Wsteig,Wtiefe,Kt,Pn,Ausfallzeit,Reparatur,Rehabilitation,Tk,Pk,InVariant
0,5515865002497708428,DN 3,4929824488020291605,3,3,0,0,0,0,0,0,0,0,0,5515865002497708428,5515865002497708428,False
1,5623248152587240406,DN 4,4929824488020291605,4,4,0,0,0,0,0,0,0,0,0,5623248152587240406,5623248152587240406,False
2,5195383577550917235,DN 5,4929824488020291605,5,5,0,0,0,0,0,0,0,0,0,5195383577550917235,5195383577550917235,False

## KMR

In [15]:
dfs[tks[3]].head(3)

,tk_merge,Name,Fk,Dn,Di,Da,S,Wsteig,Wtiefe,Kt,Pn,Ausfallzeit,Reparatur,Rehabilitation,Tk,Pk,InVariant
0,5636244102636904922,DN 25,4927972999088213410,25,"22,3","26,9","2,3",0,0,"0,19",0,0,0,100,5636244102636904922,5636244102636904922,False
1,4845758090437917162,DN 32,4927972999088213410,32,"28,5","33,7","2,6",0,0,"0,195",0,0,0,200,4845758090437917162,4845758090437917162,False
2,5728256818453294508,DN 50,4927972999088213410,50,"54,5","60,3","2,9",0,0,"0,225",0,0,0,300,5728256818453294508,5728256818453294508,False

# df pipes

In [16]:
df_pipes = s3s.generate_element_model_data_dataframe(element_type=s3s.ObjectTypes.Pipe, static_table_type_to_merge_with=s3s.ObjectTypes.PipeTable)

[2026-03-27 12:05:57,156] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-03-27 12:05:57,158] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 12:05:57,175] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-03-27 12:05:57,175] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-03-27 12:05:57,176] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH']...
[2026-03-27 12:05:58,980] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 64)

In [17]:
df_pipes.head(3)

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,tk_merge,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant
0,5442010239090746007,Rohr V-K03S V-K13S,4684070986837856878,4779752876656844188,5644881417512616095,36.42935,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,4819753480904838964,OSM: Knoten 264607345 -> Knoten 476971289; Län...,24386111,0,1,0.005,0,150,160.3,Vorlauf,,5442010239090746007,5442010239090746007,False,713620.267807,5.578828e+06,False,5442010239090746007,0,0,0,0,0,0,0,0,0,0,0,4684070986837856878,DN 150,4927972999088213410,150,160.3,168.3,4.0,0,0,0.450,0,0,0,900,4684070986837856878,4684070986837856878,False
1,4917786378639043296,Rohr V-K13S V-K23S,5103141232976878720,4779752876656844188,5644881417512616095,57.21781,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,4777543161401667328,OSM: Knoten 476971289 -> Knoten 476971283; Län...,24386111,0,1,0.005,0,125,131.7,Vorlauf,,4917786378639043296,4917786378639043296,False,713602.294600,5.578860e+06,False,4917786378639043296,0,0,0,0,0,0,0,0,0,0,0,5103141232976878720,DN 125,4927972999088213410,125,131.7,139.7,4.0,0,0,0.375,0,0,0,800,5103141232976878720,5103141232976878720,False
2,4762482310382009633,Rohr V-K23S V-K33S,5103141232976878720,4779752876656844188,5644881417512616095,40.99482,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,4893758407691905968,OSM: Knoten 476971283 -> Knoten 264607348; Län...,24386111,0,1,0.005,0,125,131.7,Vorlauf,,4762482310382009633,4762482310382009633,False,713574.061627,5.578910e+06,False,4762482310382009633,0,0,0,0,0,0,0,0,0,0,0,5103141232976878720,DN 125,4927972999088213410,125,131.7,139.7,4.0,0,0,0.375,0,0,0,800,5103141232976878720,5103141232976878720,False

In [25]:
df_pipes[["tk", "Name", "PipeTable: Kt"]].head(3)

                    tk                Name  PipeTable: Kt
0  5442010239090746007  Rohr V-K03S V-K13S          0.450
1  4917786378639043296  Rohr V-K13S V-K23S          0.375
2  4762482310382009633  Rohr V-K23S V-K33S          0.375

In [24]:
object_types = [item for item in dir(s3s.ObjectTypes) if not (item.startswith('__') and item.endswith('__')) and "Table" in item and not "Row" in item]
list = ["VarPressureTable", "VarFlowTable", "ValveLiftTable", "PumpSpeedTable", "MeasuredVariableTable", "LoadFactorTable", "ThermalOutputTable", "TemperatureTable"]
object_types2 = set(object_types) - set(list)
object_types2

{'CharacteristicLossTable',
 'CompressorTable',
 'ControlPointTable',
 'CrossSectionTable',
 'DamageRatesTable',
 'DriveEfficiencyTable',
 'DrivePowerTable',
 'EfficiencyConverterTable',
 'EnergyRecoveryTable',
 'FunctionTable',
 'NonReturnValvesTable',
 'PipeTable',
 'PumpCharTable',
 'RegulatorsTable',
 'ReturnTemperaturTable',
 'ThermophysPropTable',
 'VentOpenCloseTable',
 'WeatherDataTable'}