# Tutorial 52: General Creation of Element Dataframes

This Example demonstrates the capabilities of the class Dataframes_SIR3S_Model that extends SIR3S_Model be abilities to work directley with pandas dataframes. It is shown how to create dataframes containing information about elements such as Nodes, Pipes, etc. existing in a SIR 3S Model. The methods presented are not user-defined and neither efficient, but get you the most important information quickly. For more detailed methods of creating dataframes, see Tutorial 51.

# Toolkit Release

In [1]:
#pip install

# Imports

## SIR 3S Toolkit

### Regular Import/Init

In [2]:
SIR3S_SIRGRAF_DIR = r"C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2" #change to local path

In [3]:
from sir3stoolkit.core import wrapper

In [4]:
wrapper

In [5]:
wrapper.Initialize_Toolkit(SIR3S_SIRGRAF_DIR)

### Additional Import/Init for Dataframes class

In [6]:
from sir3stoolkit.mantle.dataframes import SIR3S_Model_Dataframes

In [7]:
s3s = SIR3S_Model_Dataframes()

Initialization complete

## Additional

In [8]:
import pandas as pd
from shapely.geometry import Point
import re
import folium
from folium.plugins import HeatMap
import numpy as np
import geopandas as gpd
from shapely import wkt
import matplotlib.pyplot as plt
import contextily as cx

# Open Model

In [9]:
s3s.OpenModel(dbName=r"Toolkit_Tutorial52_Model.db3",
              providerType=s3s.ProviderTypes.SQLite,
              Mid="M-1-0-1",
              saveCurrentlyOpenModel=False,
              namedInstance="",
              userID="",
              password="")

Model is open for further operation

# Calculate Model

In [10]:
s3s.ExecCalculation(True) # To ensure result data

Model Calculation is complete

# Generate Element Dataframes

We can use the [generate_element_dataframe()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.generate_element_dataframe) method to quickly generate basic dataframes containing all instances of hydraulic element types (Node, Pipe, etc.) in a SIR 3S model.

All model_data and most result values (self.GetResultProperties_from_elementType(onlySelectedVectors=True)) for the static timestamp are included. Result values are given as floats, unless they are in vectorized form (relevant only for pipes), in that case they are strings.

The pd.Dataframe will automatically be transformed into a gpd.GeoDataFrame if a SRID is defined in the model, after a geometry column is created.

In [11]:
object_types = [item for item in dir(s3s.ObjectTypes) if not (item.startswith('__') and item.endswith('__'))]
print(object_types) # Check for hydraulic elmement types

['AGSN_HydraulicProfile', 'AirVessel', 'Arrow', 'Atmosphere', 'BlockConnectionNode', 'CalcPari', 'CharacteristicLossTable', 'CharacteristicLossTable_Row', 'Circle', 'Compressor', 'CompressorTable', 'CompressorTable_Row', 'ControlEngineeringNexus', 'ControlMode', 'ControlPointTable', 'ControlPointTable_Row', 'ControlValve', 'ControlVariableConverter', 'ControlVariableConverterRSTE', 'CrossSectionTable', 'CrossSectionTable_Row', 'DPGR_DPKT_DatapointDpgrConnection', 'DPGR_DataPointGroup', 'DPKT_Datapoint', 'DamageRatesTable', 'DamageRatesTable_Row', 'DeadTimeElement', 'Demand', 'DifferentialRegulator', 'DirectionalArrow', 'DistrictHeatingConsumer', 'DistrictHeatingFeeder', 'Divider', 'DriveEfficiencyTable', 'DriveEfficiencyTable_Row', 'DrivePowerTable', 'DrivePowerTable_Row', 'EBES_FeederGroups', 'EfficiencyConverterTable', 'EfficiencyConverterTable_Row', 'ElementQuery', 'EnergyRecoveryTable', 'EnergyRecoveryTable_Row', 'EnvironmentTemp', 'FWBZ_DistrictHeatingReferenceValues', 'FlapValve', 'FlowControlUnit', 'FluidQualityParamSet', 'FluidQualityParamSet_OS', 'FluidThermalPropertyGroup', 'FreeDuct', 'FunctionGenerator', 'FunctionTable', 'FunctionTable_Row', 'GasComponent', 'GasMixture', 'GeneralSection', 'Gravitation', 'HeatExchanger', 'HeatFeederConsumerStation', 'HeaterCooler', 'Histeresis', 'House', 'Hydrant', 'Integrator', 'LAYR_Layer', 'LoadFactorTable', 'LoadFactorTable_Row', 'LogicalComparison', 'LogicalStorage', 'MeasuredVariableTable', 'MeasuredVariableTable_Row', 'MinMaxSelection', 'Multiplier', 'NetValve', 'Node', 'NonReturnValvesTable', 'NonReturnValvesTable_Row', 'NumericalDisplay', 'ObjectContainerSymbol', 'OpenContainer', 'Oval', 'PARZ_TransientCalculationParameters', 'PhaseSeparation', 'PidController', 'Pipe', 'PipeGroup', 'PipeTable', 'PipeTable_Row', 'PipeVertex', 'Polygon', 'Polyline', 'PressureRegulator', 'PressureZone', 'Pt1Controller', 'Pump', 'PumpCharTable', 'PumpCharTable_Row', 'PumpGroup', 'PumpOfPumpGroup', 'PumpSpeedTable', 'PumpSpeedTable_Row', 'RART_ControlMode', 'REGP_ControlParameters', 'RMES_DPTS_RmesInternalDataPoint', 'Rectangle', 'RegulatorsTable', 'RegulatorsTable_Row', 'ReturnTemperaturTable', 'ReturnTemperaturTable_Row', 'RoundRectangle', 'SIRGRAF', 'SPLZ_TimeSeries', 'SafetyValve', 'SetpointDevice', 'SolarCollector', 'StandPipe', 'Street', 'SummingPoint', 'SwitchInBlock', 'TemperatureTable', 'TemperatureTable_Row', 'Text', 'ThermalOutputTable', 'ThermalOutputTable_Row', 'ThermophysPropTable', 'ThermophysPropTable_Row', 'TransitionSymbol', 'Transmitter', 'TransportVariable', 'USCH_UserDefinedProperties', 'Unknown', 'VARA_ColorScale', 'VARA_ROWS_WidthOrScale', 'VRCT_ViewRectangle', 'Valve', 'ValveLiftTable', 'ValveLiftTable_Row', 'VarFlowTable', 'VarFlowTable_Row', 'VarPressureTable', 'VarPressureTable_Row', 'VentOpenCloseTable', 'VentOpenCloseTable_Row', 'VentValve', 'VentilatedPressureAirVessel', 'WBLZ_ThermalBalance', 'WeatherDataTable', 'WeatherDataTable_Row']

This function allows for little user definition the only paramters are element_type and tks of that element type to exclusively use. For more user defined dataframe creation see Tutorial 52.

## Node

In [12]:
(s3s.generate_element_dataframe(element_type=s3s.ObjectTypes.Node, tks=None)).head(3)

[2026-03-27 18:24:52,742] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Node ...
[2026-03-27 18:24:52,743] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Node ...
[2026-03-27 18:24:52,868] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Node
[2026-03-27 18:24:52,873] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 517 element(s) of element type ObjectTypes.Node.
[2026-03-27 18:24:52,885] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Node.
[2026-03-27 18:24:52,886] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 37 model_data properties.
[2026-03-27 18:24:52,887] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'Ktyp', 'Zkor', 'QmEin', 'Lfakt', 'Fkpzon', 'Fkfstf', 'Fkutmp', 'Fkfqps', 'Fkcont', 'Fk2lknot', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'Qakt', 'Xkor', 'Ykor', 'NodeNamePosition', 'ShowNodeName', 'KvrKlartext', 'NumberOfVERB', 'HasBlockConnection', 'Tk', 'Pk', 'InVariant', 'GeometriesDiffer', 'SymbolFactor', 'bz.Drakonz', 'bz.Fk', 'bz.Fkpvar', 'bz.Fkqvar', 'bz.Fklfkt', 'bz.PhEin', 'bz.Tm', 'bz.Te', 'bz.PhMin'], geometry...
[2026-03-27 18:24:54,056] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:24:54,056] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (517, 39)
[2026-03-27 18:24:54,130] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Node; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-03-27 18:24:54,132] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Node
[2026-03-27 18:24:54,227] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-03-27 18:24:54,229] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] 1 valid timestamp(s) will be used.
[2026-03-27 18:24:54,231] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 517 element(s) of element type ObjectTypes.Node.
[2026-03-27 18:24:54,234] INFO in sir3stoolkit.mantle.dataframes: [results] Using 73 result properties.
[2026-03-27 18:24:54,243] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-03-27 18:24:57,998] INFO in sir3stoolkit.mantle.dataframes: [results] 26884 fully NaN columns dropped.
[2026-03-27 18:24:58,350] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 10857)
[2026-03-27 18:24:58,355] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Node ...

,tk,Name,Ktyp,Zkor,QmEin,Lfakt,Fkpzon,Fkfstf,Fkutmp,Fkfqps,Fkcont,Fk2lknot,Beschreibung,Idreferenz,Iplanung,Kvr,Qakt,Xkor,Ykor,NodeNamePosition,ShowNodeName,KvrKlartext,NumberOfVERB,HasBlockConnection,Tk,Pk,InVariant,GeometriesDiffer,SymbolFactor,bz.Drakonz,bz.Fk,bz.Fkpvar,bz.Fkqvar,bz.Fklfkt,bz.PhEin,bz.Tm,bz.Te,bz.PhMin,geometry,BCIND,DP,DPH,H,HMAX_INST,HMIN_INST,IAKTIV,LFAKTAKT,P,PDAMPF,PH,PHMINMAXDIF,PH_EIN,PH_MIN,PMAX_INST,PMIN_INST,QM,RHO,T,TTR,VOLD
0,4612618373909997110,V-K2133S,QKON,543.56,0,1,5520728169779652386,4798673252636751115,5591325053703727727,-1,5029128874972463118,5611267768413515094,Anfangsknoten generiert von SirDB,3S96AE619D388EA6F4CC9F24456148E088,1,1,0,714332.858074,5.578924e+06,1,False,Vorlauf,0,False,4612618373909997110,4612618373909997110,False,False,0.2,0,4612618373909997110,-1,-1,-1,0,0,0,0,POINT (714332.858 5578924.328),17.0,0.007861,0.007861,1.121142,1.121142,1.121142,1.0,1.0,1.772026,0.012300,0.772026,0.0,0.772026,0.0,1.772026,1.772026,0.0,1000.3000,10.00000,23.338450,0.0
1,4619205996903908050,V-K983S,QKON,548.26,0,1,5520728169779652386,4798673252636751115,5591325053703727727,-1,5029128874972463118,5130743098019975840,Anfangsknoten generiert von SirDB,3S56C0B9A1652EF8E9B7AB8C5DEACA2DC4,1,1,0,713611.070733,5.578598e+06,1,False,Vorlauf,0,False,4619205996903908050,4619205996903908050,False,False,0.2,0,4619205996903908050,-1,-1,-1,0,0,0,0,POINT (713611.071 5578598.067),17.0,1.650542,1.650542,4.942585,4.942585,4.942585,0.0,1.0,5.132555,0.695561,4.132555,0.0,4.132555,0.0,5.132555,5.132555,0.0,965.8268,89.78860,0.213703,0.0
2,4619682681341516951,R-K2803S,QKON,554.99,0,1,5520728169779652386,4798673252636751115,5591325053703727727,-1,5029128874972463118,5367059433340055050,Anfangsknoten generiert von SirDB,3S7BD49C919428AD75D6EA1203195E860E,1,2,0,713542.639481,5.578805e+06,1,False,Rücklauf,0,False,4619682681341516951,4619682681341516951,False,False,0.2,0,4619682681341516951,-1,-1,-1,0,0,0,0,POINT (713542.639 5578804.842),17.0,1.542225,1.542225,3.360221,3.360221,3.360221,0.0,1.0,2.890206,0.197127,1.890206,0.0,1.890206,0.0,2.890206,2.890206,0.0,983.8152,59.76965,0.168082,0.0

## Pipe

In [13]:
(s3s.generate_element_dataframe(element_type=s3s.ObjectTypes.Pipe, tks=None)).head(3)

[2026-03-27 18:24:58,417] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-03-27 18:24:58,418] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-03-27 18:24:58,475] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:24:58,477] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:24:58,479] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-03-27 18:24:58,480] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-03-27 18:24:58,481] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-03-27 18:24:59,852] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:25:00,119] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:25:00,119] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 67)
[2026-03-27 18:25:00,183] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-03-27 18:25:00,183] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:25:00,250] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-03-27 18:25:00,250] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] 1 valid timestamp(s) will be used.
[2026-03-27 18:25:00,250] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:25:00,258] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-03-27 18:25:00,268] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-03-27 18:25:05,151] INFO in sir3stoolkit.mantle.dataframes: [results] 26724 fully NaN columns dropped.
[2026-03-27 18:25:06,946] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 16244)
[2026-03-27 18:25:06,947] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_start,MVEC_end,MVEC_sequence,PDAMPF,PHR,PMIN,PVEC_start,PVEC_end,PVEC_sequence,PVECMAX_INST_start,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMIN_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_start,RHOVEC_end,RHOVEC_sequence,SVEC_start,SVEC_end,SVEC_sequence,TI,TK,TTRVEC_start,TTRVEC_end,TTRVEC_sequence,TVEC_start,TVEC_end,TVEC_sequence,VAV,VI,VK,VOLDA,WVL,ZVEC_start,ZVEC_end,ZVEC_sequence
0,4614463970292122863,Rohr R-K4383S R-K4183S,4689226368751411179,4779752876656844188,5431845028903382031,7.780674,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,4713734746689397424,OSM: Knoten 450994211 -> Knoten 476971188; Län...,166815824,5,2,0.005,0,999,994.0,Rücklauf,,4614463970292122863,4614463970292122863,False,714262.482930,5.578857e+06,False,4614463970292122863,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (714262.483 5578857.42, 714269.543 ...",4730066059089961857,4917189080965035120,KMR,DN 999,4927972999088213410,999,994.0,1014.0,10.0,0,0,1.212,0,0,0,1950,4689226368751411179,4689226368751411179,False,0.0,7.780674,0.0,0.0,1.0,0.0,0.0,5.748007e-10,5.748007e-10,"(5.748007e-10, 5.748007e-10)",0.0123,0.0,1.615057,1.615055,1.68863,"(1.615055, 1.68863)",1.615055,1.68863,"(1.615055, 1.68863)",1.615055,1.68863,"(1.615055, 1.68863)",0.0,0.0,0.0,1000.3,1000.3,1000.3000,1000.3000,"(1000.3, 1000.3)",0.0,7.780674,"(0.0, 7.780674)",9.999994,9.999994,166.698300,174.479000,"(166.6983, 174.479)",10.0000,10.000,"(10.0, 10.0)",0.0,0.0,0.0,0.0,0.0,545.09,544.34,"(545.09, 544.34)"
1,4615723899944629797,Rohr V-K203S V-K213S,4689226368751411179,4779752876656844188,5728726059620036726,64.287240,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,4938076287810941486,OSM: Knoten 390310977 -> Knoten 1368674233; Lä...,24633100,5,1,0.005,0,999,994.0,Vorlauf,,4615723899944629797,4615723899944629797,False,713738.296567,5.579220e+06,False,4615723899944629797,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713738.297 5579219.902, 713793.23 ...",5129584372458662150,5332825919690090061,KMR,DN 999,4927972999088213410,999,994.0,1014.0,10.0,0,0,1.212,0,0,0,1950,4689226368751411179,4689226368751411179,False,0.0,64.28724,0.0,0.0,1.0,0.0,0.0,-2.983143e-10,-2.983143e-10,"(-2.983143e-10, -2.983143e-10, -2.983143e-10, ...",0.0123,0.0,3.304769,3.304770,3.59023,"(3.30477, 3.34555, 3.38633, 3.42711, 3.46789, ...",3.304770,3.59023,"(3.30477, 3.34555, 3.38633, 3.42711, 3.46789, ...",3.304770,3.59023,"(3.30477, 3.34555, 3.38633, 3.42711, 3.46789, ...",-0.0,-0.0,-0.0,1000.3,1000.3,1000.3000,1000.3000,"(1000.3, 1000.3, 1000.3, 1000.3, 1000.3, 1000....",0.0,64.287240,"(0.0, 9.183891, 18.36778, 27.55167, 36.73557, ...",9.999994,9.999994,107.366900,43.079700,"(107.3669, 98.18304, 88.99916, 79.81527, 70.63...",10.0000,10.000,"(10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0)",-0.0,-0.0,-0.0,0.0,0.0,565.84,562.93,"(565.84, 565.4243, 565.0086, 564.5929, 564.177..."
2,4621030304810285220,Rohr R-K2573S R-K2583S,5516336706687055417,4779752876656844188,5644881417512616095,3.956838,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5625716875961234775,OSM: Knoten 476971211 -> Knoten 264607350; Län...,24386111,0,2,0.005,0,100,107.1,Rücklauf,,4621030304810285220,4621030304810285220,False,713650.613400,5.578990e+06,False,4621030304810285220,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713650.613 5578990.488, 713649.498...",5070795580168283912,5725848577942138606,KMR,DN 100,4927972999088213410,100,107.1,114.3,3.6,0,0,0.325,0,0,0,600,5516336706687055417,5516336706687055417,False,0.0,0.002291,16.2622,0.064347,0.0,0.0,0.211137,-4.251046e+00,-4.251046e+00,"(-4.251046, -4.251046)",0.198023,0.000835,2.198662,2.210370,2.19866,"(2.21037, 2.19866)",2.210370,2.19866,"(2.21037, 2.19866)",2.210370,2.19866,"(2.21037, 2.19866)",-15.30376,-15.30376,-15.30376,983.7663,983.7645,983.7663,983.7645,"(983.7663, 983.7645)",0.0,3.956838,"(0.0, 3.956838)",59.86739,59.871,0.055451,0.053159,"(0.05545081, 0.05315936)",59.8674,59.871,"(59.8674, 59.871)",-0.479662,-0.479662,-0.479662,0.0,0.0,563.01,563.14,"(563.01, 563.14)"

As can be seen some result values are in vectorized form, since pipes have result values that are calculated for interior points.

## DistrictHeatingConsumer

We can specify the timestamp we want the result data for either as "2023-02-13 01:00:00.000 +01:00" or 1 meaning the second element in s3s.GetTimeStamps()[0], otherwise static is used.

In [14]:
(s3s.generate_element_dataframe(element_type=s3s.ObjectTypes.DistrictHeatingConsumer, tks=None, timestamp=1)).head(3)

[2026-03-27 18:25:07,061] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.DistrictHeatingConsumer ...
[2026-03-27 18:25:07,063] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.DistrictHeatingConsumer ...
[2026-03-27 18:25:07,137] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-03-27 18:25:07,150] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-03-27 18:25:07,150] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.DistrictHeatingConsumer.
[2026-03-27 18:25:07,150] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 55 model_data properties.
[2026-03-27 18:25:07,150] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'Beschreibung', 'Ind0', 'W0', 'Qm0', 'Tvl0', 'Trs0', 'Lfk', 'Rho0', 'Dtmin', 'Indtr', 'Trsk', 'Fktrft', 'A', 'B', 'C', 'Vtyp', 'V0', 'P1soll', 'Dpvlmin', 'Fkzep1vl', 'Tsvl', 'Zevk', 'Dphaus', 'Dprlmin', 'Fkzep1rl', 'Tsrl', 'Imbg', 'Irfv', 'Fkcont', 'Idreferenz', 'Iplanung', 'CPM', 'NumberOfVERB', 'IndtrKlartext', 'M0Estimated', 'W0Estimated', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'ShowDescription', 'PositionOfDescription', 'Angle', 'SymbolFactor', 'GeometriesDiffer', 'bz.Fk', 'bz.Indlast', 'bz.Indlfkt2', 'bz.Fklfkt', 'bz.Fklfkt2', 'bz.Fkqvar', 'bz.Fktevt', 'bz.IndlastKlartext'], geometry, end nodes...
[2026-03-27 18:25:08,227] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:25:08,367] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:25:08,367] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (337, 59)
[2026-03-27 18:25:08,438] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.DistrictHeatingConsumer; at timestamp: 2023-02-13 01:00:00.000 +01:00 ...
[2026-03-27 18:25:08,439] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-03-27 18:25:08,506] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] 1 valid timestamp(s) will be used.
[2026-03-27 18:25:08,508] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-03-27 18:25:08,510] INFO in sir3stoolkit.mantle.dataframes: [results] Using 36 result properties.
[2026-03-27 18:25:08,528] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-03-27 18:25:09,507] INFO in sir3stoolkit.mantle.dataframes: [results] 5392 fully NaN columns dropped.
[2026-03-27 18:25:09,886] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 6740)
[2026-03-27 18:25:09,898] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.DistrictHeatingConsumer ...

,tk,Name,Beschreibung,Ind0,W0,Qm0,Tvl0,Trs0,Lfk,Rho0,Dtmin,Indtr,Trsk,Fktrft,A,B,C,Vtyp,V0,P1soll,Dpvlmin,Fkzep1vl,Tsvl,Zevk,Dphaus,Dprlmin,Fkzep1rl,Tsrl,Imbg,Irfv,Fkcont,Idreferenz,Iplanung,CPM,NumberOfVERB,IndtrKlartext,M0Estimated,W0Estimated,Tk,Pk,InVariant,Xkor,Ykor,ShowDescription,PositionOfDescription,Angle,SymbolFactor,GeometriesDiffer,bz.Fk,bz.Indlast,bz.Indlfkt2,bz.Fklfkt,bz.Fklfkt2,bz.Fkqvar,bz.Fktevt,bz.IndlastKlartext,geometry,fkKI,fkKK,DH,DP,DPH,IAKTIV,INDUV,LFH,LFT,M,MHYUV,MTHUV,PHIRL,PHIVL,QM,RHOI,RHOK,TI,TK,TVMIN,W,WSOLL
0,4611752310942477664,Fernwärmeverbraucher V-K1203S R-K3683S,Gattendorf;95185;Obere Au;28;None;yes,0,139.0433,1,90,60,1,1000,3,3,60,-1,2,-0.25,-2,1,1,0,0,-1,0,0,0.2,0.3,-1,0,0,1,5029128874972463118,830887238,1,4.1903,0,"Tabelle Temperatur TEVT, TRS(t)",3.981862,34.91917,4611752310942477664,4611752310942477664,False,713675.300232,5.578705e+06,False,3,0,0.1,False,4611752310942477664,0,0,4835417738045943522,,-1,5395645951786400348,Lastfaktor thermisch,POINT (713675.3 5578705.193),4673701597187411685,4995788945387711669,17.178480,1.583809,1.583809,0.0,-1.0,0.288343,0.283131,0.318879,-0.829086,-0.829086,-3.333333e+32,-3.333333e+32,1.147966,966.0245,983.7,89.45920,60.0,68.50781,39.36751,39.36751
1,4612528660388965271,Fernwärmeverbraucher V-K1783S R-K4263S,None;None;None;None;None;yes,0,386.4134,1,90,60,1,1000,3,3,60,-1,2,-0.25,-2,1,0,0,0,-1,0,0,0.2,0.3,-1,0,0,1,5029128874972463118,1056287317,1,4.1903,0,"Tabelle Temperatur TEVT, TRS(t)",11.065940,34.91917,4612528660388965271,4612528660388965271,False,714251.332395,5.578925e+06,False,3,0,0.1,False,4612528660388965271,0,0,5554262436821166605,,-1,5395645951786400348,Lastfaktor thermisch,POINT (714251.332 5578925.001),5015101891725198603,5751808837348052764,0.070124,0.006879,0.006879,1.0,-1.0,0.000000,0.000000,0.000000,0.000000,0.000000,-3.333333e+32,-3.333333e+32,0.000000,1000.3000,983.7,10.00000,60.0,10.00000,0.00000,0.00000
2,4612562908060328263,Fernwärmeverbraucher V-K1623S R-K4103S,Gattendorf;95185;Langenbachstraße;4;None;yes,0,106.6409,1,90,60,1,1000,3,3,60,-1,2,-0.25,-2,1,1,0,0,-1,0,0,0.2,0.3,-1,0,0,1,5029128874972463118,830818182,1,4.1903,0,"Tabelle Temperatur TEVT, TRS(t)",3.053936,34.91917,4612562908060328263,4612562908060328263,False,713271.271817,5.578980e+06,False,3,0,0.1,False,4612562908060328263,0,0,4835417738045943522,,-1,5395645951786400348,Lastfaktor thermisch,POINT (713271.272 5578979.743),4965299629814639205,4779536530687993701,16.757090,1.562658,1.562658,0.0,-1.0,0.287406,0.283131,0.243774,-0.633812,-0.633812,-3.333333e+32,-3.333333e+32,0.877586,965.9670,983.7,89.55493,60.0,68.50781,30.19338,30.19338